### ISSUE TITLE
BackUp Wallet button

### ISSUE THREAD

**Issue by Pinhais** [NewEconomyMovement/NemCommunityClient#123]
What do you think about we have an button to export the wallet (the .wlt file) for back-up reason?

I discovered the Nem's Wallet is inside the root's directories on Debian by doing a "find iname / *.wlt " or something very looked like this.

On windows it can be found at C:/Users/User/Nem

On mac I have no idea where it is......

On portuguese translate we put the message for the wallet creation: "The wallet was Created sucessfully. Please, dont forget to make an back-up of your wallet!, 

The main Ideia is make easier everybody, even whith no Knowledge, to make an back-up.

Maybe the client could get flashing or something until the user make an backup file, in order to force one backup.

Im pretty sure I was not that clear, but the resume is: 

Make easier to make an backup, whatever you system is;

Maybe force the user to make an wallet backup or show strips up the words "export wallet".

![image](https://cloud.githubusercontent.com/assets/7996344/4586308/fb5c2600-5014-11e4-814d-3f8da1da8b43.png)

And whith the mouse over event: 

![image](https://cloud.githubusercontent.com/assets/7996344/4586320/4309b076-5015-11e4-90cd-1b76cd28f399.png)

Cheers!!

**Comment by fyahfox** [comment]
same as this:
https://github.com/NewEconomyMovement/NemCommunityClient/issues/26

**Comment by 21xhipster** [comment]
Could somebody help to allocate wallet file in OS X?

**Comment by fyahfox** [comment]
This is no help desk but a platform to give suggestions or report issues on the software. Please use the forum (https://forum.nemcoin.com) for questions like this.

(The wallet should be located here: Users/nem/ncc/*.wlt
If you cant find it, try searching for files on your hard drive: *.wlt)

**Comment by Jaguar0625** [comment]
This is the same as #26

**Comment by gimer** [comment]
not closing it yet, as it would be good to force user to do backup on first start

**Comment by gimer** [comment]
added warning message
