### ISSUE TITLE
Send NEM form: auto space in textbox "amount"

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#145]
The GUI inserts a space to the amount to seperate thousands. Example:
65432 -> 65 432

Since this is actually nice, it is annoying if I want to delete the 5 with the backspace key because then it only deletes the space.

I don't know how to solve this best, but this has to be reviewed.

**Comment by Jaguar0625** [comment]
This should be fixed.

**Comment by fyahfox** [comment]
It is fixed, but still not good.

Example: User enters "2040" -> it shows up as "2 040". Now you set the cursor right before the first zero and hit backspace -> 2 und 0 is deleted, because algo thinks: "hey a leading zero doesnt make sense, i delete it". BUT: maybe the user just wanted to relace a missspelled "2" into a "1"?

So again:

I think the textboxes, where users can input stuff, should not be altered by an algorithm at all. Its ok to block a-z characters in an amount textbox for example, but stop doing these auto-spaces and auto separators. You can show them in the confirmation window and in the transaction list etc. But not in that textbox.

**Comment by gimer** [comment]
ok 2040 indeed causes a problem

**Comment by gimer** [comment]
fix is not great, but as of now, proper fix would require serious redo of interface of all the modal dialogs
