### ISSUE TITLE
A click on Start or Stop harvesting does not always start or stop

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#151]
For me the button "Start local harvesting" or "Stop local harvesting" works a bit buggy. If I click on it, it often doesn't do anything. If I click again, it works.

I noticed that if I click longer (mousebutton down, wait 1 second, mousebutton up) it works better but it still happens sometimes that it doesn't work with a long click.

This is no high priority problem, but a bit annoying. Any ideas on that one?

**Comment by BloodyRookie** [comment]
fyahfox, is this still happening with the current version or was it just the result of poor performance of NIS at that time?

**Comment by fyahfox** [comment]
Works perfectly fine for me now. Even when NCC runs on the cubie 3 :)

-> close
