### ISSUE TITLE
Mouse over balance shows NEM and mNEM

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NemCommunityClient#160]
When one mouse over the Current balance, the amount is shown as xxx NEM yyyyyy mNEM

It should be xxx NEM yyyyyy uNEM or µNEM.

It is microNEM and not milliNEM.

**Comment by gimer** [comment]
@fyahfox @bluefin18 do you maybe remember where? I think it should show µXEM correctly everywhere at the moment.

**Comment by fyahfox** [comment]
This was only about the tooltip when hovering over the balance (Dashboard, Transactions, Harvested blocks). What else do you mean with "everywhere"?

I still shows:
123456 XEM 123456 µXEM

Should be (my opinion):
123,456.123456 XEM

("." will be the separation character for each language)
