### ISSUE TITLE
Remote Harvesting

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NemCommunityClient#161]
Switched on remote server. Connected to remote server, activated remote harvesting. Then switched off remote server and reconnected to local NIS. 

Remote harvesting continues to show as "Activating remote harvesting..." even after I switched off the remote server.

Also "start remote harvesting" is showing. 

This all should disappear if remote NIS is no more available.

**Comment by fyahfox** [comment]
when the activation is finished, it shows "deactivate remote harvesting" when you hover over it with the mouse. i think that is fine.

**Comment by gimer** [comment]
this report is invalid, closing it
