### ISSUE TITLE
interface of remote harvesting is confusing

### ISSUE THREAD

**Issue by nemster** [NewEconomyMovement/NemCommunityClient#168]
Some suggestions to make it more clear:

I should not see "Start remote harvesting" button in the account used to boot local node.
I should not see "Start remote harvesting" button if remote harvesting is activating but not yet active.
I should not see "Start remote harvesting" button in the accounts that are locally harvesting.
I should not see "Start local harvesting" button in the accounts that are remotely harvesting.

**Comment by fyahfox** [comment]
0.5.13-BETA

As biscodyl already mentioned...

There should be more information in the popup window when you click "Activate remote harvesting".
- activation will take 24 hrs or something...
- there will be a fee of y XEM...

**Comment by BloodyRookie** [comment]
I agree. There are so many things to do ^^

**Comment by fyahfox** [comment]
Addition to my last comment:

- Activation of remote harvesting will not actually START it (in propper english^^)
