### ISSUE TITLE
send NEM while machine (where NIS/NCC is running) is very busy

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#171]
I am running NIS and NCC on a cubieboard 3 (cubietruck). I am using the web interface on another computer and connecting through a local network to NCC.

It works good so far, but today I experienced a bad issue:
I tried to send a transaction (clicked "yes" at the confirmation message) but it was a bit slow and after some seconds it said: "Oops!  NEM Infrastructure Server is not available." and I saw the send nem form again with all the data I entered. So I clicked on "send" again, but the error came again. I did this 4 times until it finally worked (was confirmed to be sent).

Later I saw that it was sent 3 times!

**Comment by fyahfox** [comment]
Still not fixed in 0.4.48-BETA:
http://s23.postimg.org/6agidbt57/error_transactions.jpg

**Comment by Jaguar0625** [comment]
@fyahfox - is this still an issue in the latest build?

**Comment by fyahfox** [comment]
I could not reproduce the issue because the performance was increased so much that it didn't happen again, yet.

We have to find a way to trigger an error "Oops! NEM Infrastructure Server is not available." while sending. I don't know how.

**Comment by fyahfox** [comment]
0.5.16-BETA

I just saw this issue again:
- Cubie board 3 is pretty busy with current spam phase on the network and I myself am spamming 1 tx every second with the cubie.
- I manually sent 1 Million to another account, and after clicking "confirm" in confirmation popup, I got Error 500 and got back to the confirmation popup. I confirmed again, and that time it worked.
-> 1 Million was sent 2 times.

**Comment by frei-geist** [comment]
I had the same issue with 0.5.16-beta as fyahfox

**Comment by BloodyRookie** [comment]
This is a bit more tricky than one thinks ^^ But it is important so I will give it a try.

**Comment by BloodyRookie** [comment]
This happens when NIS is too busy and thus NCC runs into a timeout. But there could be other constellations too. I don't think there is enough [B]reliable[/B] information available to judge if the transaction got through or not. Therefore the only thing I can do is close the popups and display a warning.

**Comment by fyahfox** [comment]
Well if NIS is busy, then NCC should wait longer, because this is a big problem if you pay twice and didn't want to...

The longer the timeout the lower the risk that this issue leads to a "double spend", right?

**Comment by fyahfox** [comment]
I think you should increase the timeout. I usually see the transaction as pending in the dashboard in the background when I get an error message in less than 10 seconds. So if NIS is too busy and therefore not answering, just check for new pending transactions. That is also a reliable information since it comes from the blockchain, right?

**Comment by fyahfox** [comment]
Ok, thats a workaround now. Hopefully there will be a better solution in the future.
