### ISSUE TITLE
After some hours running, the transactions screens become really slow

### ISSUE THREAD

**Issue by Pinhais** [NewEconomyMovement/NemCommunityClient#194]
After some time running whith the bot, I always take a look how thing are running.

I noticed when I click the "transactions menu" and click over "Unconfirmed", incoming or outgoing, it does not respond as fast as it should. After some time thinking, there is an thrown error:

![nis transactions](https://cloud.githubusercontent.com/assets/7996344/4990391/f8793f14-696d-11e4-9c4d-63d19b2fb0ae.png)

The client is running noonstop. 

The harvested blocks interface also get slow. When you scroll down to see historical transactions, and sometime there is another error:

![ncc error](https://cloud.githubusercontent.com/assets/7996344/4990432/a0ec67ca-696e-11e4-86a8-d991645eacfd.png)

I can notice sometimes, also, the pop-up message from MOM ( the program that makes the NIs boot and start NCC on the system bar) informing "Nis is runing and completely synced and Ncc is 
running", like if they just got restarted. This last one (pop up message) Im not so sure if its a bug. 

Edit: Happend just after I click post the issu here, whith not many transactions on blocks:

![message_fromnis](https://cloud.githubusercontent.com/assets/7996344/4990540/017f1e92-6970-11e4-9cba-6b8212e1e4a2.png)

Edit: On linux mint macnhine, the historical transaction is really fast. It shown everything OK whith no error.

The force be with you yong Skywalker!!!!

=)

Edit: I restarted it, after a coulpe hours ruuning like this, and the interface got really fast. Everything are shown as expected and working!

**Comment by fyahfox** [comment]
I don't see this any longer since the performance was increased a lot.

Close?
