### ISSUE TITLE
Update Japanese アルファ→ ベータ

### ISSUE THREAD

**Issue by makoto1337** [NewEconomyMovement/NemCommunityClient#231]
Where it says アルファ版, it should say ベータ版.

![0027-01-23 13 39 32](https://cloud.githubusercontent.com/assets/6621621/5869925/6b54792e-a305-11e4-884e-90045466f1c4.png)

**Comment by BloodyRookie** [comment]
Well, what can I say Makoto, アルファ版 and  ベータ版 are just equal to me :D
Can't you fix it in the language file?

**Comment by makoto1337** [comment]
完了
