### ISSUE TITLE
Multisig UI/UX improvements

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NemCommunityClient#235]
When window opens for creation of co-signatories, there is no way of going back to choose one's account or from the address book.

When we click to Send NEM in the dashboard, there is no way of accessing the Address book. Defeats the purpose of the use of the Address book.

**Comment by fyahfox** [comment]
This is a must before launch in my opinion.

**Comment by BloodyRookie** [comment]
There will be an auto-complete function for the corresponding fields. We just didn't have time to include it in the last release.

**Comment by Jaguar0625** [comment]
Hopefully fixed in 0.5.11
