### ISSUE TITLE
Sorting of entries in address book

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#237]
I have no idea by which logic the current sorting works, but it should be possible to sort it manually by
- Account address A->Z / Z->A
- Private label A->Z / Z->A

**Comment by BloodyRookie** [comment]
Initial sorting could be done in ncc when opening the address book (probably soring by label makes sense). Not sure how hard it is to insert a field in the gui for sorting, have to take a look.

**Comment by BloodyRookie** [comment]
Will be available next release.
