### ISSUE TITLE
Sorting of own accounts

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#238]
1) The own accounts should be sorted by private label A->Z. The accounts without private label should follow after all accounts with private label and be sorted by address A->Z.

2) Also it should be possible to create account groups and assign accounts to these groups. The groups then should be sorted by group name A->Z and inside the groups the accounts should be sorted like explained in 1). If no groups were created, the accounts are just sorted like 1) without showing any group.

**Comment by jabo38** [comment]
A-Z would be very nice and is how most address books are organized.

**Comment by BloodyRookie** [comment]
1) yes with the exception that the primary account should always be in first place no matter what the label is.
2) not planned.

**Comment by Jaguar0625** [comment]
@BloodyRookie - didn't you do this already (the sorting)?

**Comment by fyahfox** [comment]
If so, then it is not working in 0.5.18-BETA

**Comment by BloodyRookie** [comment]
jaguar, no i don't think so. Will look into this.
