### ISSUE TITLE
Popup window "CONVERT ACCOUNT TO MULTISIG" doesnt close after conversion

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#239]
When you convert an account to multisig, the popup window "CONVERT ACCOUNT TO MULTISIG" does not close after you confirmed the conversion/transaction/fees.

**Comment by BloodyRookie** [comment]
Confirmed.

**Comment by BloodyRookie** [comment]
Will be fixed next release.
