### ISSUE TITLE
The way a multisig transaction is displayed in the transaction list is confusing

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#242]
0.5.4-BETA

- Instead of the message, it shows: "#cosigs x". I still think the message is more important and information about how many accounts already signed should be visible in the details.
- Instead of the fee, it shows: "n/a". I see no reason for this.
- Instead of the amount, it shows: "see details". I see no reasons for this.

**Comment by gimer** [comment]
fee is not so simple? what fee would you like and to whom (there are different parties involved: issuer, recipient, cosignatory, and multisig account itself).

Now fee, there is multisig transaction fee, inner transaction fee, and fee for every signature, which one would you like to see? or simply **total**?

Now there's small problem with total, as it's unknown until all parties cosign, so it could be confusing why the hell it changed...

**Comment by fyahfox** [comment]
@fee
I see. Hm. Maybe it should stay "n/a" until the transaction is sent (enough cosigners signed) and then the total is shown?

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/7714513/70d56540-fe7f-11e4-8bea-4d57ec1a2b9d.png)

**Comment by fyahfox** [comment]
I just noticed, this change was not applied for the transaction list, but for the list at the dashboard only.

**Comment by gimer** [comment]
@fyahfox since 6.42 both dashboard and tx view should be unified

**Comment by fyahfox** [comment]
@gimer confirmed, thx :)

I would still like to see the message of the transaction though.
-> "Instead of the message, it shows: "#cosigs x". I still think the message is more important and information about how many accounts already signed should be visible in the details."
