### ISSUE TITLE
Labels everywhere!

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#244]
Simply everywhere an address is displayed, it should be replaced with the label, if there is one in the address book. For detailed views (transactions etc.) it should display both label AND address (or make the address expandable).

**Comment by jabo38** [comment]
I would really like to see the label in the client shown instead of the address at all times.  Once I have labeled that account number with a name, it would be so much easier for me to see those names wherever possible.

**Comment by BloodyRookie** [comment]
I agree it would be an improvement, but it has not top priority. So I guess we will not see it before launch.

**Comment by gimer** [comment]
In upcoming version label should be visible in most places (in details there has to be full address), some places might be missing, and if you spot them it'd be easiest to report them. Completion should be working in upcoming release too.

![image](https://cloud.githubusercontent.com/assets/6421169/6096800/fe85db06-afa4-11e4-86c4-f5fa2308ede1.png)

**Comment by fyahfox** [comment]
nice!

**Comment by gimer** [comment]
I'm closing this issue, if you find out something missing or working incorrectly, please make another one.
