### ISSUE TITLE
Can't send nem. "send" button not turn green, only possible with "Enter"

### ISSUE THREAD

**Issue by rtstrx** [NewEconomyMovement/NemCommunityClient#245]
Many times isn't possible send nem without keyboard, "send" button does not turn green.

When I just sent nem, appears error 126, and when I open the wallet, the error 121

It is excellent for the rest

**Comment by fyahfox** [comment]
Again I can not reproduce this issue.

Do you know if your NIS was synchronized at the time you tried to send XEM?
Which browser (version?) are you using?

**Comment by rtstrx** [comment]
I haven't problems of synchronization.

My browser is chrome 40.0.2214.111 m (updated)  with avira browser safety and adblock plus. The old wallet worked perfect with the same protection

The old wallet was 100% deleted, but my address not changed. Maybe is this the problem....forgive me if that

**Comment by fyahfox** [comment]
Yes, you should create a new wallet. Please tell, if the problem is solved with that.

**Comment by rtstrx** [comment]
Excellent! with my new address everything is solved. 

Sorry community, the bug is mine.

**Comment by BloodyRookie** [comment]
Cannot confirm this behavior. Any more details? can you make a screenshot?
