### ISSUE TITLE
All options appears in the same window: Dashboard, Address Book,...

### ISSUE THREAD

**Issue by rtstrx** [NewEconomyMovement/NemCommunityClient#246]
After sending nem, the left panel does not work. Dashboard, Address Book, Transactions and Harvested blocks options appears all in the same window

**Comment by fyahfox** [comment]
I can not reproduce this issue.

Please describe more detailed how the error occurs. (Browser + version?)

**Comment by BloodyRookie** [comment]
I cannot confirm this issue too. Left panel works fine after sending NEM.

**Comment by rtstrx** [comment]
Browser: chrome 40.0.2214.111 m (updated) with avira browser safety and adblock plus.

I will create a new account nem. The old wallet it was deleted, but not my old address. I'm sure that is the problem. 
Sorry for the inconveniences.

**Comment by rtstrx** [comment]
Sorry, the bug is mine, because I don't create a new address.
