### ISSUE TITLE
Transfer Fee Calculation is Wrong

### ISSUE THREAD

**Issue by Jaguar0625** [NewEconomyMovement/NemCommunityClient#249]
It looks like the fee calculation is always assuming a message; even when there is no message. It probably makes sense to treat an empty message as no message.

Repro Steps:
- Create a transfer for 25 NEM with no message

Expected:
- Fee is 2 NEM

Actual:
- Fee is 4 NEM

**Comment by gimer** [comment]
fixed in a99f228603ca90f4bf0b5a92289683c9f7923097
