### ISSUE TITLE
Address Book Should Do Some Address Validation

### ISSUE THREAD

**Issue by Jaguar0625** [NewEconomyMovement/NemCommunityClient#250]
We should only allow valid NEM addresses to be added to the address book. We can't do a lot of validation, but we can at least check that the network matches and the length is correct.

Repro Steps:
(1) Add 00DBA34E6404538F20C9B57E6C18DEBC06753756976D76F0A9EC54D45AD2E46B23 to the address book
(2) Try to remove 3485D9-8EFD7E-B07ADA-FCFD1A-157D89-DE2796-A95E

Expected:
(1) Address cannot be added because it is invalid

Actual:
(1) Address is added
(2) Address cannot be removed because the UX truncates it to 40 characters but the address book stores the entire address

**Comment by BloodyRookie** [comment]
Fixed: https://github.com/NewEconomyMovement/NemCommunityClient/commit/2ff6a992e790cd046bab4defb7c15d354cc40fc8
