### ISSUE TITLE
NCC web interface -> Settings -> Remote Server: Not possible to change port

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#251]
0.5.4-BETA

It is still not possible to change the default port (7890) to something else at the NCC web interface Settings page.

This is needed if you are running more than 1 IPv4 node behind 1 router.

**Comment by gimer** [comment]
so you're forwarding different ports on your router to different machines running NIS, right?

**Comment by fyahfox** [comment]
correct
