### ISSUE TITLE
Show private key for backup purposes

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#252]
There should be an easy way to show the private key of every account to be able to write it down on paper (or whatever the user wants to do to have a backup).

Of course a warning should be displayed too like "Never save this private key unencrypted anywhere on your computer or phone. Only write it down on a paper and put it to a safe place." or something like this...

I think that an "export wallet" feature alone is not enough because a lot of people will lose their password for the wallet or save the password unencrypted or whatever.

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/6656299/81b9a2c8-cb25-11e4-9d36-bd61efa7ed8f.png)
![image](https://cloud.githubusercontent.com/assets/6421169/6656303/9beff5d4-cb25-11e4-9059-3bc3919be150.png)

**Comment by gimer** [comment]
817e8307c9f3a26352d9cb16d377c99077d56693

**Comment by fyahfox** [comment]
Very good solution!
