### ISSUE TITLE
Allow multisig account to be its own signatory

### ISSUE THREAD

**Issue by makoto1337** [NewEconomyMovement/NemCommunityClient#257]
I think it makes sense from a UX perspective to allow an acct to be a signatory on itself for a multisig account. I think often you just want to add signatories to your own account for protection, rather than giving up control.

**Comment by gimer** [comment]
@Jaguar0625 do we want this? (in other words: should we allow multisig account to make MultisigSignatures? should he be able to innitiate transactions too?)

**Comment by gimer** [comment]
closing this after talking with @Jaguar0625

**Comment by gimer** [comment]
(linked commit is for #252 not 257)
