### ISSUE TITLE
Send from address book issue

### ISSUE THREAD

**Issue by filchef** [NewEconomyMovement/NemCommunityClient#259]
When account is signer for another multisig account is impossible to send any transaction from address book from this signer account.I have in my wallet 3 accounts one multisign and 2 cosigners so now from address book is impossible to send any coins from this 2 cosigners accounts give me the same error like boot 3 account is multisig.

**Comment by gimer** [comment]
can you post screenshot with an error?

**Comment by filchef** [comment]
So problem was with old config file when I change language to English this not happened  after I change to Bulgarian again this not happened.
