### ISSUE TITLE
Client options to back up wallet

### ISSUE THREAD

**Issue by Thingamajigger** [NewEconomyMovement/NemCommunityClient#26]
Hope i'm following protocol here - it's the first time i've used Github :D

Another idea i suggested was in-client options to allow the user to back up their wallet - save them having to search through directories for a specific file (Assuming they know what file in the first place!) which isn't exactly what i call user friendly for Average Joe.

It would just be another step in the right direction for the average joe to use NEM if this were implemented.

**Comment by fyahfox** [comment]
same as this:
https://github.com/NewEconomyMovement/NemCommunityClient/issues/123
