### ISSUE TITLE
Error with with syncing status display

### ISSUE THREAD

**Issue by renolteng** [NewEconomyMovement/NemCommunityClient#262]
NCC NIS 0.5.5  Firefox 35.0.1
It said "NIS is synchronizing. At block 5764, est. 3 days behind."
But the latest transaction of mine is now. And I can successfully make and receive new transactions.
I think there's something wrong with syncing status display.

**Comment by gimer** [comment]
I assume you see UNCONFIRMED transactions, that is rather normal.
when it come to sending it's possible (see #316 for discussion).

If this is about something else, please report it again.
