### ISSUE TITLE
Dashboard: "See all transactions" displaced in Firefox (35.0.1)

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#265]
0.5.5-BETA

http://s15.postimg.org/nc7gspeff/gui_glitch.png

I don't see this in Chrome or Opera, only Firefox (35.0.1 now).

**Comment by gimer** [comment]
This is due to addition of "vested balance" right below Balance. We're gonna fix it either in next iteration or at launch, thx for reporting

**Comment by gimer** [comment]
same as #317

**Comment by fyahfox** [comment]
lol i thought i opened that already, but didn't find it^^
