### ISSUE TITLE
changing label on old primary account

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#268]
I made a brand new wallet.  Opened, ported in my private key in a new account.  Set the new private key account as primary.  Went to change label on the other account (old primary) via the gear icon and get a message 127 address book does not contain this address.  Can manually paste address into address book to make label.

**Comment by jabo38** [comment]
99% of this issue was solved in the latest release but one instance still exists.  

I made a brand new wallet.  Opened, ported in my private key.  Set the new private key as primary.  Went to change label on the other account via the gear icon and get a message 127 address book does not contain this address.

The rest of the time when I try to change a label through the gear icon, it works

**Comment by Jaguar0625** [comment]
@BloodyRookie - can you look at this?

**Comment by BloodyRookie** [comment]
I just tested it and it works. I think i fixed it with this commit some time ago:

https://github.com/NewEconomyMovement/NemCommunityClient/commit/fd13490188f1ee9a92757d98a225c9f38652f293

Unless jabo38 still has problems i think we can close this issue.

**Comment by gimer** [comment]
@jabo38 can you test, and close if it's not an issue now

**Comment by jabo38** [comment]
I tested this and things are working well.  I will close the comment.  

Thanks :-)
