### ISSUE TITLE
Show "(at block xxxxx)" in the status bar behind "NIS is synchronized!", not behind balance

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#269]
I think the information about the current height makes more sense in the status bar.

As long as NIS is synchronized, the block height is not interesting for average joe, so that shouldn't be visible behind the balance.
If NIS is not synchronized, there should be a warning at the balance. Something like "might be inacruate, NIS not synchronized" or whatever.

**Comment by gimer** [comment]
@Jaguar0625 I think we still show current height SOMEWHERE

**Comment by fyahfox** [comment]
as i said -> status bar? :D

**Comment by gimer** [comment]
@fyahfox you mean the one on top, hmm it's bit small, but could do the trick

**Comment by fyahfox** [comment]
its pretty wide i think :D no need for a second line...

Example:
NIS is synchronized! (current block height: 53058)

**Comment by Jaguar0625** [comment]
@gimer agree to show height somewhere

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/6653431/23e35c8a-ca93-11e4-8a0a-1b3f5a5aa6ac.png)
![image](https://cloud.githubusercontent.com/assets/6421169/6653437/4e5d9610-ca93-11e4-8aed-d111788afa6f.png)
