### ISSUE TITLE
couldn't harvest

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#271]
I had over 2000 XEM for more than 2000 blocks and NEM won't let me harvest.  I am not sure why.

This may or may not be related to the fact that I am running this NEM node on my Mac.  Interestingly enough nembex doesn't see my Mac even though I can send and receive XEM.  I think my router was configured for Windows so this might also be part of the problem.  I mention these things here because I am not sure if they are important or not.  

http://s25.postimg.org/v9h5sk767/Screenshot_2015_02_13_12_04_10.png

**Comment by gimer** [comment]
@jabo38 right under balance, you have vested balance, that's the answer to your issue :)
