### ISSUE TITLE
Uninstall problems

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#28]
When uninstalling, it should be asked if wallet and config-files should be deleted, too.
Desktop and start menu shortcuts should be deleted as well.

I think this is pretty important, because during an alpha-testing it happens pretty often that you uninstall and install again.

**Comment by Jaguar0625** [comment]
@fyahfox is this still an issue?

**Comment by fyahfox** [comment]
I never used the webstart version again since then... So, I can't tell.

**Comment by Jaguar0625** [comment]
Webstart is no longer supported.
