### ISSUE TITLE
In standalon version when using monitor issue

### ISSUE THREAD

**Issue by filchef** [NewEconomyMovement/NemCommunityClient#283]
This is memory issue - when you using runMon.bat  switches:-Xms512M -Xmx1G for decrease memory which use NIS don't work.

**Comment by gimer** [comment]
you mean MON does not work with those switches, or NIS does not work with those switches?

**Comment by filchef** [comment]
NIS does not work with this switches just use 1GB memory when you start from runMon.bat.I did not see switches like in runNis.bat in runMon.bat.

**Comment by gimer** [comment]
It might not be obvious, but if you start via MON, you need to alter config.properties inside mon directory.

Corresponding option is {{nis.vmOptions = }}

**Comment by filchef** [comment]
Thank you @gimer so we need good readme inside in the package where are explained all config properties before launch

**Comment by gimer** [comment]
@filchef btw, default values there should actually be `nis.vmOptions = -Xms512M -Xmx1G`, have you noticed something else there?

**Comment by filchef** [comment]
Yes I use 
`<addr>` nis.vmOptions = -Xms512M -Xmx768M

**Comment by gimer** [comment]
@filchef I mean, default options right after downloading package should already be `nis.vmOptions = -Xms512M -Xmx1G`

So I think this issue could be closed
