### ISSUE TITLE
New Installer

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NemCommunityClient#286]
Works fine on Windows 8. But would be good if we can get this two things done so that it is more seamless:

Newer version should be installed in the same directory and overwrites the old one.
Config properties should not be overwritten or have another file where the config is user's config. In the absence of a user config, use the default config that comes with the installer.

This way, everything is so neat and have less user intervention.

**Comment by fyahfox** [comment]
+1

Clean uninstall of the old version, but keeping the custom configs would be really nice.

**Comment by gimer** [comment]
keeping configs would be bit hard to do, as sometimes format of config.properties changes. handling that would be bit troublesome.

but when it comes to directory, y, we need to do that

**Comment by gimer** [comment]
I forgot to do close it, but it's partially done.
installer tries to reuse dir, config file should not be overwritten
