### ISSUE TITLE
Translation Issue (Bulgarian Language)

### ISSUE THREAD

**Issue by filchef** [NewEconomyMovement/NemCommunityClient#290]
In last release 0.5.13 in settings was string "Convert other account to multisig".
In Bulgarian language this string is to long and not gather in window and because of it cut first 3 letter in all links inside of settings window.
I don't know if is to big problem for GUI dev. to resize the letters font to solve problem like this.

**Comment by filchef** [comment]
Problem is not solved in 0.5.16

**Comment by gimer** [comment]
this is screenshot from upcoming version, is it how it should look like?

![image](https://cloud.githubusercontent.com/assets/6421169/6585989/477c6e36-c776-11e4-8042-ee7a54944f73.png)

**Comment by filchef** [comment]
yes I replace word **Преобразувай** with word **Превъни** which is more short

**Comment by gimer** [comment]
should be bit better now
![image](https://cloud.githubusercontent.com/assets/6421169/6648740/cd6fcfd8-c9dd-11e4-96dd-6e86382022f6.png)

**Comment by gimer** [comment]
menu in other languages is now wrong
![image](https://cloud.githubusercontent.com/assets/6421169/6655735/9ef3b94e-cb09-11e4-9a2b-3e3dd9f29686.png)

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/6655780/c0137332-cb0c-11e4-980e-0097a8e3ac02.png)
