### ISSUE TITLE
Error 602 isn't an error but a function

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#292]
When I start up NEM and the database is loading I get an error every time for 602 telling me that I "cannot perform any operations until "the" (edit on my part) database is fully loaded."  And while this is true, it isn't really an error.  I can just see some newbies turning on their NEM wallets for the first few times and getting this error and thinking that something was already broken.  

It would be nice if the pop-up removed the sad face, and "error 602" and instead had a happy face and a big "Welcome! Right now your database is loading.  After it is fully loaded you can start using the NEM client."

**Comment by gimer** [comment]
good idea, we'll try to do that

**Comment by jabo38** [comment]
On version 0.5.16 when I click runMon in the stand alone folder package, I get the wallet landing page.  After I log in, it now says error 305, and suggests among other things to restart.  In reality everything is fine and just the blocks are loading.  In the past there use to be a yellow bar with a block loading counter that was much less confusing.  That was nice but isn't necessarily needed, but a message that tells people to restart could confuse newbies.

**Comment by gim913** [comment]
a) standalone is not supposed to be run by newbies.
b) standalone has delayed block loading set to false, and that is on purpose, as most people run it on remote nodes, where that is more sensible default
