### ISSUE TITLE
Mac copy and paste problem

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#297]
On my MacBook Air when I click on the gear icon next to account numbers, there is an option to "copy address to clipboard".  Once this is done and I paste into a transaction send box, I get the error about things developers did not forsee.  

But when I drag the mouse over the account number and highlight it, then copy, then paste into a transaction box, it works fine.  

Also, I noticed that the "copy address to clipboard" on my Mac is sometimes darkened as if it is highlighted, even if the mouse is not hovering in that section, and when it is darkened then it won't copy anything at all.

**Comment by gimer** [comment]
have you checked if it copies anything at all? (do you have flash installed, copying requires flash, can't do that from within javascript)

**Comment by Jaguar0625** [comment]
I just tried this and can't repro.
