### ISSUE TITLE
Strange textbox at popup when stopping 'remote harvesting'

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#298]
0.5.13-BETA

When you stop remote harvesting, a popup is displayed where you have to enter your wallet password. There is also a strange textbox without any description:
http://s29.postimg.org/qicdi08pz/stop_remote_harvesting.png

**Comment by gimer** [comment]
it's "Due by", it's been fixed if you see it in 0.5.16 or later let us know

**Comment by fyahfox** [comment]
I confirm this is fixed in 0.5.16-BETA.
