### ISSUE TITLE
Convirt to multisig account problem

### ISSUE THREAD

**Issue by renolteng** [NewEconomyMovement/NemCommunityClient#299]
This problem were there from 0.5.4 to 0.5.13.
When I'm trying to convirt an account to multisig and used two accounts from different wallet of the same NCC as cosign account, Error 306 happened, the convirt couldn't finish.

**Comment by gimer** [comment]
I'll try to reproduce that

**Comment by gimer** [comment]
iirc problem is related to pasting addresses

**Comment by BloodyRookie** [comment]
The problems is due to the pasted account addresses having no known public key which is needed for the modification. I changed the implementaion to show an error message if the public key of any cosignatory is unknown.
