### ISSUE TITLE
AVAST doesn't like NEM

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#300]
I get a pop-up every couple of minutes telling me that AVAST has blocked an infection.  I had to just put AVAST in silent mode.  This is one of the most popular anti-viruses so I think it is important.  

I have reported it many times to AVAST that NEM is okay over a couple of months but it doesn't seem to help.  

http://postimg.org/image/ul2st4l6z/

**Comment by gimer** [comment]
there's nothing we can do about it. It's avast fault not ours.
You can check if there's any setting that would let you to ALLOW connections to port 7890 (and to your port 7890).
Maybe this will help: https://www.avast.com/no-no/faq.php?article=AVKB25
