### ISSUE TITLE
Convert to multisig -> add cosigner -> error when pasting an address

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#303]
When you convert an account to multisig and add a cosigner, there is an error if you paste an address from clipboard. It is suggested to "Just use" the address, but that address is cut off:
http://s13.postimg.org/l5zh9mxg7/add_cosigner_error.png

I don't see a reason in that "Just use" suggestion at all. It is fine how it is at "Send XEM".

**Comment by gimer** [comment]
There is a bug when pasting address with "-", as ui also tries to add, them. Hence invalid result.

**Comment by fyahfox** [comment]
But it works perfectly at the "Send XEM" popup window...
