### ISSUE TITLE
"local harvesting" is running -> activating remote harvesting

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#306]
0.5.16

When "local harvesting" is running and you activate "remote harvesting", it keeps harvesting, which is fine. After 1440 blocks (when remote harvesting is really activated) the button "Stop local harvesting" changes to "Start remote harvesting".

I think it would be good if "remote harvesting" starts automatically if "local harvesting" was running before and not turned of.

Btw: I couldn't start remote harvesting in that case, because it said that the limit for this server is reached. Of course I can't be sure if in the meantime somebody used my NIS for remote harvesting... (There were several hours between when "remote harvesting" was really activated and when I clicked on "start remote harvesting".) But I don't think so. It is morelikely a bug.

Similar problem:
When I deactiaved "remote harvesting", so the status was "deactivating remote harvesting...", I started "local harvesting" again. But I think it is in fact not harvesting. I still have to see, if this is really true, but it looks like it.

**Comment by fyahfox** [comment]
I can confirm that local harvesting in fact started after the deactivation of remote harvesting (which takes 1440 blocks). So the question is: Why isn't it possible to do local harvesting while deactivation is in progress?

**Comment by gimer** [comment]
as you've noticed, it is "deactivating", so during that time you still can harvest with remote account, but not with local one. You can START "local harvesting", but as you've noticed it won't start until 1440 blocks will pass.

Rationale behind it's simple: you should be able to do: deactivate remote harvesting + start local, and go away from machine, once it's deactivated, local harvesting will start working.

It's actually a feature.

Unfortunatelly, the first part (automatic activation of remote harvesting) is currently not possible. closing the issue as of now, you can reopen it if you want milestone to be assigned.

**Comment by fyahfox** [comment]
Thanks for the explanation. We need in client information for stuff like that. Nobody is going to understand why "local harvesting" doesnt work althouth there is a button to click "Start local harvesting" AND it is showing that it is started. Maybe insert a popup with that information in this specific case.
