### ISSUE TITLE
Auto start harvesting when NIS is started

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#308]
This is not the same as #301.

It would be nice to have another option in NIS config.properties: If there is a private key set to auto boot the NIS, it should be able to set true/false an option to auto start harvesting on NIS start up.

**Comment by gimer** [comment]
That actually might not be as easy as it sounds, but we'll see what we can do

**Comment by Jaguar0625** [comment]
Updated NIS properties.
