### ISSUE TITLE
change in address label didn't show up correctly in confirmation details

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#309]
I changed a bunch of labels of random addresses to Gandolf and his 4 wizards in training.  

Gandolf was going to the Lonely Mountain so he left his account in control of the apprentices.  

When I was turning Gandolf's account into a multisig account I could enter in the wizard in training's name into the cosignatory field just fine, but when I saw the confirmation details, I noticed all the old names showed up.  

That was weird because at the same time NCC was showing me the same accounts having different names in two different boxes at the same time.  I would have guessed it would have showed me one or the other set in both instances.  

Suspecting that my computer might have been the problem because it had been on for many days and had sent over 100,000 transactions via my spam bot, I tried a reboot.  Upon rebooting the correct address labels appeared in the transaction details.  

http://s25.postimg.org/xng53ycsv/address_label_2.png

**Comment by gimer** [comment]
so bottom right is before reboot, and bottom left after reboot?

**Comment by jabo38** [comment]
the bottom right was before reboot and was wrong; as well as the top right which is the "convert to multisig confirmation".  Both of those reflect older address book labels.

The bottom left was after reboot and is correct; as well as the top left labels for the multisig names.  They reflect the correct, updated, and current names in the address book.

**Comment by jabo38** [comment]
I will add this was a one time only bug and I haven't had it replicated since.  If I remember though, there might have been a couple of times where something a bit similar happened but not in the same circumstance; that basically I was seeing the old address label for an account instead of the new one.  Even though it is not a big issue for me, I wanted to bring it to the main devs attention just in case.

**Comment by jabo38** [comment]
I repeated the problem.  https://www.dropbox.com/s/k7d2oxkfbzdogbq/address%20label%20problems.png?dl=0
