### ISSUE TITLE
Display addresses of cosigners of a multisignature account

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#311]
0.5.16-BETA

Till now there is no way to show the addresses of the configured cosigner of a multisignature account in the GUI. Would be nice to have that... ;)

**Comment by gimer** [comment]
@fyahfox to make it straight, do you want to:

a) display MULTISIG accounts, that given account is a cosignatory of (well that's actually visible in send nem dialog already) so I suppose you mean
b) for MULTISIG account display it's cosignatories.

in b, where would you display it?

**Comment by fyahfox** [comment]
Yes, I meant b).

I suggest this: http://s21.postimg.org/kguk1ketz/cosignatory_list_suggestion.png

It would be very good to see the current account next to balance anyway, because whenever it is loading slow, you are sure which account balance you are looking at.

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/6657728/427c3f4c-cb54-11e4-8259-10ecccfe3729.png)

**Comment by fyahfox** [comment]
The account details window is very nice!

But you don't like to see the label (or address if no label is present) of the current account next to "Current Balance"?
"It would be very good to see the current account next to balance anyway, because whenever it is loading slow, you are sure which account balance you are looking at."

**Comment by gimer** [comment]
@fyahfox not sure if I understand you, this "current balance" is in the background. I've attached it on the screenshot only to make it visible, where "view cosignatories" is.

**Comment by fyahfox** [comment]
nevermind, you implemented the "loading" warning

**Comment by fyahfox** [comment]
I reconsidered.

It would be way more logical to have a "View Account Details" in the gear menu (next to account address on the left side). This should be present for all accounts, not only multisig accounts, because people might want to see additional information for any account.

You could then include the "display private key" IN the popup window of "View Account Details", that would make even more sense and you have one menu item less in the gear menu.

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/6766246/b5adbb5e-cffe-11e4-8a0e-6f4a0c21d3ec.png)

The "display private key" is a separate issue, not sure if we'll be doing that (if you think it'd be good, create separate isssue).

**Comment by fyahfox** [comment]
thanks!
