### ISSUE TITLE
Problem with switching to a certain account from primary

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#315]
0.5.16-BETA

I noticed that there is a problem when switching from my primary account to a certain account (it has a pretty long private label, see screenshot: http://s9.postimg.org/3yuhaosxb/account_switch_bug.png).

I click on it, but it just doesn't switch. One time it did switch, but it switched back to primary after few seconds.

If I switch to any other accounts (no problems with other accounts), I can then switch to the long private label one without problems.

**Comment by BloodyRookie** [comment]
Is this problem occuring only when using a slow NIS like a cubie or a general observation? I had this "not switching to another account" problem back when NIS/NCC was too slow during spamming phases.

**Comment by fyahfox** [comment]
I will have to look into that later, but what I can definitely say: Switching to other accounts is no problem, but that one with the longer private label is a problem often.

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/6625773/7a0976b4-c8f2-11e4-9ff0-2bb598298339.png)

Can't confirm, I'm switching from primary to long label account, without problems, if you'll figure out what it is drop us a line.
