### ISSUE TITLE
Fresh installation (installer): problem with auto booting NIS

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#322]
0.5.18-BETA (installer), Win 7, 64-bit Java 8

- All previous versions of NEM software uninstalled and working/user data deleted.
- Fresh installation with the 0.5.18 installer -> check the option to run the wallet after closing the installer
- NCC web interface opens up -> create new wallet and log in
- at this time, the status bar is yellow and says "NIS needs to be booted. Boot a local node blah blah"
- dropdown menu (top right) is used -> click on Boot Local Node (which is NOT grayed out) -> nothing happens (no popup windows appears), even if tried repeatedly
- Close NCC -> Restart NCC -> Log into the new wallet -> the status bar is yellow and says "NIS is synchronizing. At block XYZ etc." and the "Boot Local Node" is now grayed out.

After some investigation, we assume that the auto-boot procedure (which is enabled by default) does not work, if NIS is not ready yet. This probably leads to a faulty state and the manual boot procedure (via NCC dropdown menu) doesn't work either.

I was not able to reproduce this issue with the standalone (=log into the wallet when NIS is not ready to be booted yet), because I then see a popup where I am supposed to enter the node name and another popup window is displayed with a warning, that NIS is not available. Whenever NIS is ready, I can boot it by clicking "boot" in the popup window.

**Comment by gimer** [comment]
when nis is not ready, auto-boot will simply return error, and you'll have to boot manually (that is sane and sort of expected).

the bug was actually caused by the fact, that right after creating new wallet UI was getting bad addressbook data.
