### ISSUE TITLE
Boot remote NIS with priv key that has balance not possible

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#330]
0.5.19-BETA

- auto-boot at wallet log in activated
- when you log into the wallet, a warning is displayed: sure you want to boot with that private key (has balance)?
-> Click YES
--> It doesn't boot anyway.

then if you try to boot the node manually (dropdown menu in NCC gui)
-> warning displayed... -> click BOOT
--> Error occurs:
"Oops!

ERROR 401

This operation cannot be completed because it might leak a private key by sending it to a remote NIS"

**Comment by gimer** [comment]
as of now, we will not allow booting remote node from within NCC

**Comment by fyahfox** [comment]
I think that is a good solution. It means that whoever sets up a node, has to make sure the node is booted either via a bootkey which is entered in NIS config.properties or runs a NCC on the same local machine to boot the node.

thanks for resolving this so fast
