### ISSUE TITLE
Is there a solution for the Unsafge software warning?

### ISSUE THREAD

**Issue by Pinhais** [NewEconomyMovement/NemCommunityClient#333]
I installed the Nem 0.5.18 on my windows 8.1 and I got this warning message:

![nem ecosystem installer](https://cloud.githubusercontent.com/assets/7996344/6699354/01388670-cce0-11e4-97f5-e01df48b2fe4.png)

Is this a problem?

**Comment by gimer** [comment]
I don't think there's any, when nem will have higher adoption this will probably go away on it's own.
