### ISSUE TITLE
Stop remote harvesting: textbox without description

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#336]
0.5.19-BETA

When you stop remote harvesting, a popup window is displayed and there is a textbox without a description:
![stop_remote_harvesting](https://cloud.githubusercontent.com/assets/6625264/6729092/49a7d938-ce2f-11e4-8b25-e01d840f7d03.PNG)

**Comment by gimer** [comment]
that was leftover from some old version, I'm not sure why and how it got there
