### ISSUE TITLE
Include "Display Private Key" feature in Account Detail View

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#347]
I think it would be good to have less entries in the gear/context menu of an account. And since a private key IS a detail of an account, it would be just logical to have this feature inside the "View Account Details" view.

**Comment by gimer** [comment]
not sure if we'll make it, as "account details is common for ALL accounts, not only those that belong to you.

**Comment by fyahfox** [comment]
when do accounts (which are in the ncc accounts list) not belong to you?

**Comment by gimer** [comment]
the "view details" dialog is used for ANY account (i.e. every TX in transactions list)

**Comment by fyahfox** [comment]
Well then have a simple "if account is in wallet, then display "show priv key"" or something like that? ;)

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/8071731/178e5d18-0f0d-11e5-807d-e450e45553d8.png)

fixed in de43b9aa8bc3d240b0fc205fe6bd75a814cecfb0

**Comment by fyahfox** [comment]
Oh nice!
