### ISSUE TITLE
problem losing my internet

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#349]
this may or may not be related to NEM, but it seems like it to me.  When I am running NEM on my Windows Desktop and I have had it on for more than 4+ days along with heavy usage of programs/apps something strange will happen.  I will lose my internet connection for Internet explorer and Chrome.  I can no longer visit websites.  But other parts of my internet like Telegram and Dropbox will still work.  Only a restart resolves this issue.  When I leave my computer on for days at a time and no NEM running, this doesn't happen.  At the same time, if I am running NEM on my Macbook Air. I can leave it running for a week no problem and it runs just fine (but I don't use the Mac for anything else, just NEM).

**Comment by gimer** [comment]
@Jaguar0625 @BloodyRookie I don't see how nem could be the caues, maybe you guys have some ideas?

**Comment by fyahfox** [comment]
@jabo38 How often did you reproduce the error?

**Comment by jabo38** [comment]
if I leave my computer on long enough (for a few days), it seems to happen most of the time with certain releases, and other releases not so much.  the latest version is affected.  interestingly enough, the NEM client is just fine and maintains internet, and so does dropbox and messengers, but IE or Chrome can no longer access webpages.

**Comment by gimer** [comment]
@jabo38 do you use some AV/firewall?

**Comment by fyahfox** [comment]
that seems like a DNS problem. not sure if it is NEM related.

**Comment by patmast3r** [comment]
@jabo38 Hard to believe that this is related to NCC. 
I suggest to install glasswire which will provide you a lot of info on the activity on your computer in a user-friendly manner. Maybe it'll help you pinpoint the problem. 
It will notify you of DNS changes and alike as well.

**Comment by gimer** [comment]
closing as invalid
