### ISSUE TITLE
Put down arrow below account and keep the cog static.

### ISSUE THREAD

**Issue by kodty** [NewEconomyMovement/NemCommunityClient#359]
currently as soon as you hover over the account drop down, the cog turns into an arrow. the arrow and cog should be two separate icons and static. ie. put a down arrow below the "primary account" and stop the cog changing.. this will leave a permanent indication to users that they can click the down arrow to open the drop down, currently there is nothing to tell users they can open other accounts by clicking there. perhaps have it get brighter when hovering over it or when the drop down is opened.

**Comment by fyahfox** [comment]
+1

This would be less confusing for new users.

**Comment by fyahfox** [comment]
this is urgent now, a lot of people have problems with this and think they lost their funds when they close their wallet, log in again and have the primary account displayed.
