### ISSUE TITLE
Direct symbols for "Close Wallet" and "Close NCC" 

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#361]
I think it would be a lot better like this:

![close_wallet_program-01](https://cloud.githubusercontent.com/assets/6625264/6900437/b5db0514-d706-11e4-8298-e6146844ccd9.png)

I can send the resources in any size (46x46px e.g.) or vector files. Just tell me what you need, if you want to implement it.

**Comment by gimer** [comment]
will try to do it

**Comment by fyahfox** [comment]
https://www.dropbox.com/s/lm5co2gniu04ip9/close-ncc_close-wallet_resources.zip?dl=0

**Comment by gimer** [comment]
fixed in af2b7b9d9d93dd76bbdb6e8376b0771934975653
