### ISSUE TITLE
import private problem

### ISSUE THREAD

**Issue by tianfate** [NewEconomyMovement/NemCommunityClient#363]
when we  import a private  which a space in the start or in the middle ,the private can not be imported into.

the client  warn:  
ERROR 500
An error occurred that the development team did not have foreseen. Apologies for this, maybe a retry might help. Otherwise, please open up an issue within the NEM NIS/NCC community.

It may change his warn  as:  the private you put  conlude a space,please scan it.

**Comment by fyahfox** [comment]
1) Spaces in front or at the end should get auto deleted.
2) Invalid chars (anything but 0-9 and a-f) should be blocked while entering. If pasted, warn that the pasted key is invalid.
3) Invalid priv keys (too short or too long) should not lead to unhandled exceptions, but easy to understand warning message.
