### ISSUE TITLE
"vested balance" displayed wrong?

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#364]
0.6.25-BETA

What you see on this screenshot, should not be possible:
Vested balance is 0 but "delegated harvesting" was started.

![auswahl_004](https://cloud.githubusercontent.com/assets/6625264/6939541/f0e08496-d86d-11e4-83ae-f8480c668fc9.png)

**Comment by gimer** [comment]
can you provide account number? (I think it is possible - you can start delegate harvesting whenever you want, it's just transaction).

**Comment by fyahfox** [comment]
I thought you can only start local/delegated harvesting when you have a vested balance of at least 10k XEM?

**Comment by gimer** [comment]
OH, I've missed that (I thought you started "activation"), ok will check it

**Comment by gimer** [comment]
I think this has been fixed in 0.6.28
