### ISSUE TITLE
needed "vested balance" for harvesting wrong?

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#365]
0.6.25-BETA

When you try to start harvesting for an account with insufficient funds, a warning is displayed saying that you need 1.000 XEM to harvest. Truth seems to be 10.000 XEM though?

![auswahl_005](https://cloud.githubusercontent.com/assets/6625264/6939587/8751a504-d86e-11e4-9fbf-4529f66294f7.png)

**Comment by patmast3r** [comment]
Also it should say vested XEM instead of just XEM. This is a common source of confusion for people.

**Comment by oliversimon** [comment]
https://github.com/NewEconomyMovement/NemCommunityClient/pull/398
