### ISSUE TITLE
Windows installer doesnt rename folder when updating previous version

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#386]
When you install 0.6.26 when 0.6.25 is already installed, everything works fine, but the folder "nem-0.6.25" in c:\programs\ is not renamed to new version.

Don't forget to update the shortcuts to the new directory then also.

**Comment by gimer** [comment]
all new releases of installer should not append version to the directory (unless previous version had it, but it's not something that we could change easily).
