### ISSUE TITLE
nis.additionalHarvesterPrivateKeys

### ISSUE THREAD

**Issue by jadedjack** [NewEconomyMovement/NemCommunityClient#393]
More than one key in nis.additionalHarvesterPrivateKeys causes nis to crash
I have tried space separated and pipe separated keys with the same result.

**Comment by gimer** [comment]
I think it wass supposed to be ":"

**Comment by jadedjack** [comment]
That doesn't seem to work either

**Comment by Jaguar0625** [comment]
it is pipe-separated, so use "|"

**Comment by jadedjack** [comment]
That worked ,
Thank you sir
