### ISSUE TITLE
Config files not readable in windows

### ISSUE THREAD

**Issue by ghost** [NewEconomyMovement/NemCommunityClient#396]
The config.properties files are not readable in the windows installation.
They are in Unix format where a new line is represented by a LF character. We need a combination CR/LF for files in DOS/Windows:

**Comment by jadedjack** [comment]
# IN UNIX ENVIRONMENT: convert Unix newlines (LF) to DOS format.
 sed "s/$/`echo -e \\\r`/"            # command line under ksh
 sed 's/$'"/`echo \\\r`/"             # command line under bash
 sed "s/$/`echo \\\r`/"               # command line under zsh
 sed 's/$/\r/'                        # gsed 3.02.80 or higher

**Comment by patmast3r** [comment]
never heard of this before. 
Is this a freshly unpacked config.properties or has it been on a unix machine prior to opening it on a windows host?

**Comment by jadedjack** [comment]
No , it it directly from the nemwallet installer for windows. Do you use windows?

**Comment by fyahfox** [comment]
jadedjack is right, the lines end with a LF character. but i still have no problems reading it with windows?

**Comment by jadedjack** [comment]
OK, how does a user edit a config-properties file like this?
![2015-05-04 03-40-17 config properties - notepad](https://cloud.githubusercontent.com/assets/11894442/7451570/6b239c74-f20f-11e4-9e9b-ab78c20881f1.png)

**Comment by fyahfox** [comment]
I see. I only use better editors, so I didn't notice that.

But yes, people will use Editor. So this should be fixed soon.

**Comment by gimer** [comment]
that's been fixed in 0.6.31, if not for some reason feel free to reopen
