### ISSUE TITLE
Email addresses as wallet names don't work

### ISSUE THREAD

**Issue by makoto1337** [NewEconomyMovement/NemCommunityClient#400]
1) Make a wallet like xxx@yyy.com
2) try to open the wallet after restarting NCC. It won't work.

**Comment by Jaguar0625** [comment]
ractive is viewing the '.' as a field access expression :/

**Comment by fyahfox** [comment]
Then don't allow "." as wallet names, when creating a new wallet?

**Comment by gimer** [comment]
fixed in f736a9daa85a3d74e0bdf85c6fdfd8fa8ae60da2
