### ISSUE TITLE
Message signing and verification

### ISSUE THREAD

**Issue by ghost** [NewEconomyMovement/NemCommunityClient#407]
It would be nice to be able to sign a text with your account key, to prove that the account is yours.

http://www.reddit.com/r/Bitcoin/comments/18qy88/bitcoin_message_signing_and_verification/

**Comment by fyahfox** [comment]
+1

**Comment by gimer** [comment]
it's somewhere on our roadmap, under the name "token generation", will be there sooner or later.

**Comment by fyahfox** [comment]
This should not be closed until its implemented..?

**Comment by gimer** [comment]
![image](https://cloud.githubusercontent.com/assets/6421169/8439088/fde6cc48-1f69-11e5-8aca-45aa8ad80c41.png)

**Comment by gimer** [comment]
this feature is not fully functional, and will be expanded in future versions
