### ISSUE TITLE
message in log: "FAILURE_MULTISIG_INVALID_COSIGNERS"

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NemCommunityClient#412]
0.6.28-BETA

How to reproduce:
- initiate a multisig transaction
- cosign with just 1 cosignatory and 1h due by time
- wait until 1h is over (dont sign with the other cosignatories!)
-> the message "FAILURE_MULTISIG_INVALID_COSIGNERS" appears on all node's logs.

I think we don't need this message in the logs, it can just be silent.

**Comment by BloodyRookie** [comment]
Will be fixed in next version.
