### ISSUE TITLE
Increasing the number of characters for Encrypted messaging

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NemCommunityClient#413]
The limitation on the number of characters that can be put into the encrypted messaging is very prohibitive. It basically renders the encrypted messaging useless.

With message encryption being a core feature, this feature should be seriously enhanced to at least allow 150 Characters at the minimum to make any sensible use of it.

**Comment by BloodyRookie** [comment]
The message field for a transaction is for commenting the transaction, what comment is 150 characters long? For long messages it is probably better to have an own transaction type.
That being said I agree that the 48 characters are indeed a bit short cause a hash as hex-string doesn't fit in.

**Comment by Jaguar0625** [comment]
The idea is to eventually have another type that allows longer messages.

**Comment by gimer** [comment]
incresed to 160, will be avail after fork
