### ISSUE TITLE
Export wallet problem

### ISSUE THREAD

**Issue by gimer** [NewEconomyMovement/NemCommunityClient#415]
I'm not exactly where the problem happens... exported walled is corrupted.

See exportWalletZip in wallet.js and exportWallet in WalletController.

**Comment by Jaguar0625** [comment]
Well, there is no import, so what do you expect to happen?

Also, files in ZIP are not encrypted :/

**Comment by gimer** [comment]
(closed wrong issue)

**Comment by gimer** [comment]
fixed by @BloodyRookie in 91a6341a99732bb6a5d8ed9e6426ab277ca86559

**Comment by gimer** [comment]
fixed in 8e3b23cb85a8886f469dddd205d1ee39b1a23f80, merged to testnet
