### ISSUE TITLE
Japanese text doesn't load

### ISSUE THREAD

**Issue by makoto1337** [NewEconomyMovement/NemCommunityClient#418]
Japanese (and a few other languages) seem to be broken and won't load the text in NCC.

![image](https://cloud.githubusercontent.com/assets/6621621/7826194/c6dac7f0-0451-11e5-9cd6-77441620a5b4.png)

**Comment by fyahfox** [comment]
It seems that not a specific language is broken. I could switch to Japanese without problems and then tried out all other languages. At some point (German in that case) it just didnt switch any more. Even a restart of NCC did not help.

**Comment by gimer** [comment]
fixed in 0.6.31 rel
