### ISSUE TITLE
activating delegated harvesting from multisig, additional signers 742 error

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#424]
Testnet 6.36

I have been trying to activate delegated harvesting on accounts in multisig.  The first part of the transaction goes okay, but when the cosigners try to cosigner, I get the error. 

ERROR 742
Multisig signature transaction rejected. Associated multisig transaction is not known to NEM network.

**Comment by gimer** [comment]
weird, that should be working fine, I'll try to verify it

**Comment by jabo38** [comment]
The problem persists on 0.6.37

**Comment by jabo38** [comment]
problem persists on 0.6.38

**Comment by BloodyRookie** [comment]
Confirmed, thx jabo38.

**Comment by gimer** [comment]
fixed in NewEconomyMovement/nem.core#61aac76ec4e605f0fb1eb3627b633b51b2e888a4
