### ISSUE TITLE
better notification of old version in NCC

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#427]
Right now in NCC there is panel that explains what the latest version is, but there is no warning if somebody is up to date, and if they aren't no call to action.  Maybe when a client is out of date there could be a message in the window asking them to update with a link to follow to http://nem.io/install.html.

![image](https://cloud.githubusercontent.com/assets/10395907/8224314/29cc1e5c-15c0-11e5-92d7-40357483793d.png)

**Comment by gimer** [comment]
that actually is already done, and will be avail in upcoming version

![image](https://cloud.githubusercontent.com/assets/6421169/8439055/ccfc3b04-1f69-11e5-94f5-eb4a97ecdf18.png)
