### ISSUE TITLE
export wallet feature creates failed wallets

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NemCommunityClient#428]
I'm using testnet 6.37 and when I manually copy the wallets in a file and then later paste them back in NEM it works, but if I use the export wallet feature and then try to paste them back into my wallet, then I get error 121. 

I have also tested this on 6.31 on the mainnet and got this same error.  I do have a lead.  On mac the files that were manually copied and pasted looked one way, but the files that came out of the export zipped folder looked a different way.  The corrupted wallet file was labeled "exec" and had a different icon.  
![screenshot 2015-07-08 05 02 13](https://cloud.githubusercontent.com/assets/10395907/8556068/8c1b6238-252f-11e5-952b-3be2f6eea11e.png)
![screenshot 2015-07-08 05 03 06](https://cloud.githubusercontent.com/assets/10395907/8556069/8c1cde92-252f-11e5-9cfb-89b4a8327f67.png)

**Comment by jabo38** [comment]
by changing the wallet name of the failed wallets by putting a "+" in the space, I was able to get the wallet to work again on testnet

**Comment by gimer** [comment]
hopefully fixed in 6f9351723cdf730b93a6abad41958c0c0e16113d

**Comment by jabo38** [comment]
Working fine 0.6.29
