### ISSUE TITLE
With language dutch selected, the NEM logo is replaced by text  (see screenshot)

### ISSUE THREAD

**Issue by Xpedite** [NewEconomyMovement/NemCommunityClient#441]
![capture](https://cloud.githubusercontent.com/assets/15026757/10563840/6b406a0c-759a-11e5-9b33-db5db219198c.JPG)
This text overlaps the account info label so it prevents the ability to select other accounts. 

(I'm looking into it , shouldn't be too difficult to fix )

**Comment by Xpedite** [comment]
The issue is caused because the image file name was translated in the dutch.js file. As a result of this, the image can't be found and thus the alt text NEM - NEW ECONOMT MOVEMENT is displayed. This however is not specific to dutch so it may be best to fix this.  
Two options that I can think off : 
1. Drop the NEW ECONOMY MOVEMENT in the applicable html pages ( landing , start and wallet)
2. Change the style from h1 tag to something so that the current text fits 
Any preferences ?

**Comment by fyahfox** [comment]
Good catch. Which option is better to fix should be decided by the devs. @BloodyRookie @gimer ?

**Comment by gimer** [comment]
change the style is preferred, what's in dutch lang file, that broken the logo display? it should be same one across all the languages (except pirate)

**Comment by Xpedite** [comment]
what's in dutch lang file, that broken the logo display?  : logo: 'images/nem_logo.png', was translated to logo: 'afbeeldingen/nem_logo.png', and thus the alt text was shown.

I'll see if I can find a style that fits...
