### ISSUE TITLE
Cannot create a new wallet (0.6.70)

### ISSUE THREAD

**Issue by Thies1965** [NewEconomyMovement/NemCommunityClient#447]
Creating a new wallet is broken. NCC displays a 306 unexpected error after a new name and the password was provided.
The files for the wallets are created but even opening the wallets leads to the same 306 unexpected error.

**Comment by Thies1965** [comment]
It seems that the config.properties file is not correctly set-up to use the testnet. The following entry has to be changed:

nem.network = testnet

Otherwise it leads to the above mentioned error.
@gimer could you take care of that?

**Comment by gimer** [comment]
all the testnet builds have `nem.network` set to `testnet` as a default, this actually is not an issue
