### ISSUE TITLE
limit txs

### ISSUE THREAD

**Issue by Jaguar0625** [NewEconomyMovement/NemCommunityClient#68]
<a href="https://github.com/vicvegas"><img src="https://avatars.githubusercontent.com/u/8005891?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vicvegas](https://github.com/vicvegas)**
_Friday Jul 25, 2014 at 13:31 GMT_
_Originally opened as https://github.com/NewEconomyMovement/NIS/issues/29_

----

not a bug but an idea: should txs be limited to 5 per min in both the client and by api calls? help cut down on the spam/network bloat?

**Comment by fyahfox** [comment]
This is done and it is at 120 transactions per block (=minute).

**Comment by gimer** [comment]
@Jaguar0625 should we close this issue?
